### ISSUE TITLE
how to host ssl sites?

### ISSUE THREAD

**Issue by hubaishan** [rsanden/wf-apache-php-fpm#1]
how to host ssl (https) sites?
are there changes in httpd.conf

**Comment by rsanden** [comment]
No, SSL is handled by the front-end Nginx server. The request is then proxied with HTTP to this apache instance over the localhost interface, and encryption of the response is likewise handled by Nginx on the way out. So there's nothing to do in httpd.conf regarding SSL.

**Comment by hubaishan** [comment]
Thank you
